const pagesContants = {
    homeES: "inicio",
    homeEN: "home",
    aboutUSES: "quienes-somos",
    aboutUSEN: "about-us",
    contactoES: "contactanos",
    contactoEN: "contact",
    blogES: "blog",
    blogEN: "blog",
    terminosCondicionesES: "terminos-y-condiciones",
    terminosCondicionesEN: "terms-and-conditions",
    avisoPrivacidadES: "aviso-de-privadidad",
    avisoPrivacidadEN: "privacy-notice",
    bolsaTrabajoES: "bolsa-de-trabajo",
    bolsaTrabajoEN: "works",
    galeriaES: "galeria",
    galeriaEN: "galeria",
    educationES: "educacion",
    educationEN: "education",
    mesaDirectivaES: "mesa-directiva",
    mesaDirectivaEN: "mesa-directiva",
    amarteMexicoES: "amarte-en-mexico",
    amarteMexicoEN: "amarte-in-mexico",
    afiliateES: "afiliate",
    afiliateEN: "afiliate",
    directoriosES: "directorio-profesionales",
    directoriosEN: "directorio-profesionales",
}

export default pagesContants;